# Generated by Django 2.1.1 on 2018-09-11 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together={('datetime', 'name')},
        ),
    ]
